services:
  - type: web
    name: chainlit-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py --host 0.0.0.0 --port $PORT --public
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

